### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/app-starter#12]
I've noticed that there are several gitignore rules for files in the project folder even on files that are meant to be edited.

Is there some reason for this that I'm not understanding or should they be removed from the composer package?

**Comment by spekary** [comment]
Could you give examples.

**Comment by kpirbhai** [comment]
One I just found that apparently I've missed before is in project/includes/connector.

The gitignore file is set to to ignore all *.class.php

Every file in that folder is specifically meant to be modified.

**Comment by spekary** [comment]
OK, just created a fix over in qcubed/framework
