### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by laceja** [qcubed/app-starter#16]
The directory structure of the downloaded application is inconsistent with the scripts.  For example, it is looking for the directory "framework", when the actual directory is named "qcubed".  Changing the directory name to "framwork" doesn't work because, other scripts are looking for "qcubed" and also cannot find the file "qcubed.inc.php".

**Comment by olegabr** [comment]
Thank you for the report!
I'll fix the issue in the `qcubed/qcubed` repo too.
