### ISSUE TITLE
Install error: qcubed/cache

### ISSUE THREAD

**Issue by vallter2** [qcubed/app-starter#21]
Hi,

i need to install qcubed v4, but every time install stop on qcubed/cache (without any message).

Thanks

**Comment by kukrik** [comment]
Please describe the problem in more detail. How did the composter work?
I also have a similar problem that I ignore.

This is the message to me:
 ```
Cannot create cache directory /user/dir/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache.
Cannot create cache directory /user/dir/.composer/cache/files/, or directory is not writable. Proceeding without cache.
```
How do you install with a composer? I use this command as follows:

`composer create-project --stability=dev qcubed/app-starter your_dir_name dev-qcubed4`

or

`sudo composer create-project --stability=dev qcubed/app-starter your_dir_name dev-qcubed4`

I hope I'm a little helpful.

**Comment by vallter2** [comment]
**I use command:**
composer create-project --stability=dev qcubed/app-starter your_dir_name dev-qcubed4 (when remove dev-qcubed4, I got 3.1.1 version)

**It just stop on this line...**
![composer](https://user-images.githubusercontent.com/28445312/51000808-70672e80-152e-11e9-96ae-61d55c2d26c9.jpg)

**Comment by kukrik** [comment]
Hmmm really? 

Have you tried another option: `sudo composer create-project --stability=dev qcubed/app-starter your_dir_name dev-qcubed4`?

Maybe there are rights??? Are you still in the right place? Before you go to the place where the developments are made? As an example, you need to go to the desired location: `cd /Users/dir/etc/...`?

**Comment by vallter2** [comment]
That command not work...
"sudo" is not recognized as an internal or external command...

**Comment by vallter2** [comment]
I solved problem with this command:
composer clear-cache
