### ISSUE TITLE
Composer Error install qc4 app-starter

### ISSUE THREAD

**Issue by vmakre** [qcubed/app-starter#22]
I tested this on Vagrant 2.0.1 machine , with 
PHP 7.1.11-1+ubuntu14.04.1+deb.sury.org+1 .
` composer create-project --stability=dev qcubed/app-starter project4 dev-qcubed4`
and composer stopped at:
```
    Failed to download phpunit/phpunit-mock-objects from source: The process "git clone --no-checkout 'https://github.com/sebastianbergmann/phpunit-mock-objects.git' 
 '/var/www/html/qcubed4/project4/vendor/phpunit/phpunit-mock-objects' && cd '/var/www/html/qcubed4/project4/vendor/phpunit/phpunit-mock-objects' && git remote add composer 'https://github.com/sebastianbergmann/phpunit-mock-objects.git' && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist
```
I think this is not qcubed problem but some libraries are old . 
[https://github.com/composer/composer/issues/8099](https://github.com/composer/composer/issues/8099)
Can someone advise me ?. @spekary  @matthiaz

**Comment by matthiaz** [comment]
Really? Weird. I have done exactly that earlier this week without issue...

**Comment by vmakre** [comment]
Yes same command works on another computer
Vagrant 2.1.13 
PHP 7.1.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 11 2019 14:13:16) ( NTS )
A lot of differences  between each other, vagrant version , ubuntu 14 vs 16 who knows .
Maybe VirtualBox sync of shared folders not supporting symlinks , who knows .

[https://vomtom.at/running-vagrant-with-symbolic-links-enabled/](https://vomtom.at/running-vagrant-with-symbolic-links-enabled/)

**Comment by vmakre** [comment]
I will close this thread because I solved it and it isn't qcubed problem.
Thanks @matthiaz
